### ISSUE TITLE
SWA output

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/SOILWAT2#13]
Right now I am working on saving the outputs from SOILWAT and am specifically working on saving the available soil water. My question is where, and which variable, is the available soil water stored in? Kyle showed me the input file with SWABULK and in the SW_Output.c file there is a variable called swaBulk and a function called get_swaBulk. the function get_swaBulk isnt called, at least not with the parameters I am running STEPWAT with and when I print the variable all I get are 0.000's. So I am wondering where the value for the available soil water is in SOILWAT?

Thanks,
Brenden

**Comment by dschlaep** [comment]
SOILWAT2 does not calculate available soil water content because it cannot do it properly. The variable ‘swcBulk’ that you see in the structure ‘SW_SOILWAT_OUTPUTS’ (defined in SW_SoilWater.h) is a stub that is left over from old versions of SoilWat. It and the associated code could be removed without harm.

Available soil water content (SWA) is defined as the soil water content (SWC) which can be extracted, i.e., it is calculated as SWC - SWC[crit]. Where SWC[crit] is the soil water content at a critical soil water potential (SWP[crit]) which is the lower pressure limit an extraction agent can suck up water. The relationship between SWP and SWC can be described by so called ‘pedotransfer’ functions and is dependent on the soil texture. For agronomical application with well-watered crops, it was historically assumed that SWC[crit] at SWP[crit] = -1.5 MPa. However, we are working in arid and semiarid systems where most/all plant species can extract water well below -1.5 MPa. Hence, SWC[crit] is species-specific - or at least plant-group specific; thus, the simple interpretation of the concept of SWA is tenuous or useless in vegetation that is composed of species with differing SWC[crit].

Historically, SoilWat was treating vegetation as one type of green slime which had one value for SWC[crit] and thus could provide one output of SWA. More recently, SoilWat represents vegetation as composed of four functional plant types (grasses, shrubs, forbs, and trees). These groups are known to vary considerably in SWC[crit]. Thus, SoilWat cannot calculate one SWA that is valid for the simulated vegetation and it stopped providing SWA output. This is to prevent the need to output a separate SWA for each functional group and because calculating SWA is simple based on the provided output of SWC and separate information on SWC[crit] for a specific plant species/objective.

However, the wrapper rSFSW2 calculates SWA for each user-requested SWP value.

Daniel

**Comment by kpalmqui** [comment]
Thank you Daniel for your time and the detailed description you provided. We were hoping to move SWA into STEPPE to use it for overhauling how current resource availability is calculated each year (currently based solely on transpiration). Since SOILWAT2 cannot calculate a single SWA value, do you have any thoughts on what related output variables within SOILWAT2 might be utilized instead? Is SWC off limits then too?

**Comment by dschlaep** [comment]
SWC is fine. 

An idea: SOILWAT2 requires SWP[crit] as input per functional plant group. With that you could calculate a SWA for each functional group separately on the STEPPE side assuming all of SWC would become available for that functional group, i.e., 

- SWA[grasses] = SWC - SWC[crit, grasses]
- SWA[shrubs] = SWC - SWC[crit, shrubs]
- ...
Of course, this is then only the potential SWA -- in absence of competition for the resources.

**Comment by BrendenBe1** [comment]
SWC is passed back to STEPWAT; its stored in a structure defined in sxw.h and stored in SXW.swc in SW_output.c. If that variable has the necessary information I can just save that to the csv, unless you prefer to convert it in the way that Daniel suggested.

**Comment by kpalmqui** [comment]
I think SWA is preferable to SWC. It seems like Daniel has come up with a potential solution to calculate SWA on the STEPPE side. Daniel and I will discuss with Bill briefly in our meeting tomorrow and I will get back to you Brenden on how to proceed. 

Regardless,it would be good to move forward with exporting SWC to a .csv file, as part of our larger effort to get all of the SOILWAT2 output saved each year and iteration that STEPWAT2 runs. Once you complete that, you can work on getting all of the SOILWAT2 variables exported to csvs. It would be great to have the option to save SOILWAT2 variables at multiple timescales (daily, weekly, monthly, yearly) as well. Perhaps we could utilize the outsetup_v31.in file for this purpose?

**Comment by kpalmqui** [comment]
Update: code to calculate SWA will now happen in STEPWAT2 (see issue #24).
