### ISSUE TITLE
Estimation of code coverage

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/SOILWAT2#20]
- estimate code coverage of unit tests
- report this estimate

**Comment by Zachary-Kramer** [comment]
Most IDEs will report how much of the code is covered. Most notably, non-enterprise editions of Visual Studio use a plug-in [OpenCover](https://github.com/OpenCover/opencover) to do so.

**Comment by dschlaep** [comment]
OpenCover is Microsoft and seems a ["code coverage tool [only] for .NET 2 and above (Windows OSs only - no MONO)"](https://github.com/OpenCover/opencover).

I would favor a solution that would integrate well with a CI. What do you think about using [coveralls](https://coveralls.io)? I set it up for our rSOILWAT2 repository [badge - via travis CI](https://coveralls.io/github/Burke-Lauenroth-Lab/rSOILWAT2). They appear to integrate with [c/c++ github repositories and travis](https://coveralls.zendesk.com/hc/en-us/articles/201342799-C-C-).

**Comment by dschlaep** [comment]
I am just realizing that the OpenCover repository is using [coveralls](https://coveralls.io/github/OpenCover/opencover) for themselves as well!

**Comment by Zachary-Kramer** [comment]
Coveralls looks like a nice tool and appears to integrate well with GitHub. I don't see any better option.

I noticed that for rSOILWAT2, code coverage takes into account the src folder. Do we want this? As a side note, when you click a file within src, coveralls cannot find the file.

**Comment by dschlaep** [comment]
> I noticed that for rSOILWAT2, code coverage takes into account the src folder. Do we want this? As a side note, when you click a file within src, coveralls cannot find the file.

I opened an [issue](https://github.com/Burke-Lauenroth-Lab/rSOILWAT2/issues/36) for that in rSOILWAT2.

However, it is to be expected that https://coveralls.io cannot find the source files from SOILWAT2 within the src/ folder in the rSOILWAT2 repository. This is because SOILWAT2 is only a submodule in rSOILWAT2. No?

**Comment by Zachary-Kramer** [comment]
Yes I assume it's because of the submodule, though GitHub can access submodule files just fine, so it's probably just coveralls not being able to access the SOILWAT2 repo (or a lack of submodule support).
