### ISSUE TITLE
Apply biomass effects in its own function

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/SOILWAT2#23]
Per #22:

> Yearly updates of CO2-effects to biomass: this is implemented by calling 'SW_VPD_init()' by function '_begin_year()'. The function 'SW_VPW_init()', however, includes calculations which are not dependent on the CO2-effects, i.e., the monthly interpolation of litter, pct_live, and lai_conv. They should be in a separate function that is indeed only called at the beginning. E.g., 'SW_VPD_init()' and 'SW_VPW_update()' which does the yearly updates.

**Comment by Zachary-Kramer** [comment]
@dschlaep This is a low-priority enhancement that you could help with, if you think it should be included in the initial merge with master branch. I don't have any current changes that will conflict with changes in SW_VPD_init

**Comment by Zachary-Kramer** [comment]
I misunderstood the issue and now have some concerns about implementing the suggestion. 

SW_VPD_init is called yearly because not only do CO2 effects need to be applied, but the interpolation needs to be re-done for the variables that changed. Now, I'm only changing a few variables (yearly biomass, yearly pct_live for tree), but they are indirectly used in many other calculations, so the functionality that I would need to extract would be the majority of SW_VPD_init.

For instance, I would need to extract most of this code just because I changed the yearly forb biomass:
```		
                if (GT(v->fractionForb, 0.)) {
			lai_standing = v->forb.biomass_daily[doy] / v->forb.lai_conv_daily[doy];
			v->forb.pct_cover_daily[doy] = lai_standing / v->forb.conv_stcr;
			if (GT(v->forb.canopy_height_constant, 0.)) {
				v->forb.veg_height_daily[doy] = v->forb.canopy_height_constant;
			} else {
				v->forb.veg_height_daily[doy] = tanfunc(v->forb.biomass_daily[doy],
						v->forb.cnpy.xinflec,
						v->forb.cnpy.yinflec,
						v->forb.cnpy.range,
						v->forb.cnpy.slope); /* used for vegcov and for snowdepth_scale */
			}
			v->forb.lai_live_daily[doy] = lai_standing * v->forb.pct_live_daily[doy]; /* used for vegetation interception */
			v->forb.vegcov_daily[doy] = v->forb.pct_cover_daily[doy] * v->forb.veg_height_daily[doy];
			v->forb.biolive_daily[doy] = v->forb.biomass_daily[doy] * v->forb.pct_live_daily[doy];
			v->forb.biodead_daily[doy] = v->forb.biomass_daily[doy] - v->forb.biolive_daily[doy]; /* used for transpiration */
			v->forb.total_agb_daily[doy] = v->forb.litter_daily[doy] + v->forb.biolive_daily[doy]; /* used for bare-soil evaporation */
		} else {
			v->forb.lai_live_daily[doy] = 0.;
			v->forb.vegcov_daily[doy] = 0.;
			v->forb.biolive_daily[doy] = 0.;
			v->forb.biodead_daily[doy] = 0.;
			v->forb.total_agb_daily[doy] = 0.;
		}
```

With this in mind, is it worth creating a new function?

**Comment by dschlaep** [comment]
ok, sounds reasonable.
