### ISSUE TITLE
Change @CO2EFFECTS output

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/SOILWAT2#24]
New requirements have been requested due to the change to how tree's biomass is affected.

* Sum total biomass across all PFTs, including the unaltered tree biomass
* Sum live biomass across all PFTs

This involves recreating the column "TreeBiomass", along with new columns "ForbBiolive", "ShrubBiolive", "GrassBiolive", "TreeBiolive", "TotalBiolive", and the removal of "TreePctLive".

This also requires changes in rSOILWAT2

**Comment by Zachary-Kramer** [comment]
@CaitlinA please confirm that we want all of the following columns: Year, ShrubBiomass, GrassBiomass, ForbBiomass, TreeBiomass, TotalBiomass, ShrubBiolive, GrassBiolive, ForbBiolive, TreeBiolive, TotalBiolive, BioMult, StoMult

**Comment by CaitlinA** [comment]
Is BioLive <- Biomass * PctLive. If so, all of these columns look good.

**Comment by Zachary-Kramer** [comment]
This is almost complete (in fact, it _is_ complete for SOILWAT2), however there seems to be a bug on rSFSW2 master that is causing issues in the tree data, which in turn is messing up the output. I'll be looking more into this.
