### ISSUE TITLE
Eliminate the R specific print statements?

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/SOILWAT2#33]
For instance 

			#ifndef RSOILWAT
				 printf("\ntl_by_sl");
					for (j = 0; j < nlyrs + 1; j++)
					   printf("[%i,%i]=%3.2f ", i, j, st->tlyrs_by_slyrs[i][j]);

			#else
				  Rprintf("\ntl_by_sl");
					for (j = 0; j < nlyrs + 1; j++)
					   Rprintf("[%i,%i]=%3.2f ", i, j, st->tlyrs_by_slyrs[i][j]);
			#endif

**Comment by Zachary-Kramer** [comment]
Are you suggesting to get rid of all Rprintf statements (by replacing with printf), or that low-level debug output should only be done in SOILWAT2?

printf will show up in R console output, but won't sink to a file, so if the output is useful at all it'd be best to keep the Rprintf statements.

**Comment by dschlaep** [comment]
What about a redefining the function `printf` at compile time?
Something along the idea of
```
#ifdef RSOILWAT
  int printf( const char* format, ... ) {
    Rprintf(format, ...);
  }
#endif
```

or maybe through a macro (similar to how we are currently defining `mkdir` depending on the OS 
```
#ifdef RSOILWAT
  #define printf(format, ... ) Rprintf(format, ...)
#endif
```

I don't know whether the function redefinition or the macro would be better?

Then above example could be simplified to 
```
			 printf("\ntl_by_sl");
				for (j = 0; j < nlyrs + 1; j++)
				   printf("[%i,%i]=%3.2f ", i, j, st->tlyrs_by_slyrs[i][j]);
```

**Comment by Zachary-Kramer** [comment]
Is there a functional difference? I personally think the macro is cleaner and is more clear what we're doing, plus it's consistent with mkdir

**Comment by dschlaep** [comment]
I defined the macro `swprintf`. We now need to update and unify all the `printf`/`Rprintf` statements to `swprintf`
