### ISSUE TITLE
Allow CO2 coefficients to vary for each plant functional type

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/SOILWAT2#57]
As argued for in https://github.com/Burke-Lauenroth-Lab/SOILWAT2/pull/22#issuecomment-312260577, I do think we need the capacity to provide different coefficient values for each of the four plant functional types -- as in the suggestion below (with identical values until we have better data): 

```
# CO2 Coefficients: Coeff1 * ppm^Coeff2
# Biomass
# Grasses	Shrubs		Trees		Forbs
  0.127             0.127               0.127              0.127    # Coeff1
  0.3501          0.3501             0.3501            0.3501 # Coeff2
# WUE
  22.464         22.464             22.464           22.464    # Coeff1
  -0.531          -0.531              -0.531            -0.531      # Coeff2
```

**Comment by Zachary-Kramer** [comment]
This is implemented locally, will close it when rSOILWAT2 supports the additional output
