### ISSUE TITLE
prod.in default inputs for CO2 coefficients are confusing

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/SOILWAT2#58]
The default inputs for CO2 coefficients are confusing because there are four numbers (as if each number applies to one of the four plant functional types -- as used for the inputs earlier in the file).

```
# CO2 Coefficients: Coeff1 * ppm^Coeff2
# Biomass
# Coeff1 Coeff2
  0.127 0.3501 0. 0.
# WUE
# Coeff1 Coeff2
  22.464 -0.531 0. 0.
```

==> What are the zeros?

**Comment by Zachary-Kramer** [comment]
If I remember correctly, the issue was that VegProd.c expects 4 values for every line. The CO2 code only reads in 2, but 4 are required (which I forget why they are). I will revisit this code to see if this reasoning still holds or if there's a better way around it.

**Comment by dschlaep** [comment]
See comment #57: the four values per line are for the four plant functional types.

**Comment by Zachary-Kramer** [comment]
I'm implementing it like such:

![image](https://user-images.githubusercontent.com/16931318/30903994-d9e0b2d6-a370-11e7-81a5-aa65bd420526.png)

Since issue #57 is a functional issue, and this one is a question, I'm going to combine them into just 57
