### ISSUE TITLE
Make the implicit assumption that input biomass is at 360 ppm CO2 explicit

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/SOILWAT2#59]
The current default coefficients for the CO2-scaling function
```
Coeff1 * ppm^Coeff2
```

are estimated with the assumption that the reference biomass was under 360 ppm CO2. That means that the biomass values inputted via `prod.in` are by SOILWAT2 considered to be the values for the year with 360 ppm CO2.

This is not clear to the user.

I suggest that we update the CO2-scaling equations such that the user can specify either a reference year or a reference CO2 concentration as additional input.

**Comment by Zachary-Kramer** [comment]
Was this intended to be assigned to soilwat_co2_effects?

**Comment by dschlaep** [comment]
Yes, thanks for catching this. I updated and assigned this issue to the 'soilwat_co2_effects' milestone.

**Comment by Zachary-Kramer** [comment]
In this case, could you clarify the functionality?

> I suggest that we update the CO2-scaling equations such that the user can specify either a reference year or a reference CO2 concentration as additional input.

What should happen if the reference concentration is different than the implicit 360 ppm?

**Comment by dschlaep** [comment]
Currently, I get for grasses based on RCP85 data a multiplier = 1 at [CO2] > 360 ppm instead of expected [CO2] = 360 ppm (with commit f57240d7dceffb9ff51d0f7fd0f3e77aec0bb14d):

```
bio_mult[1995] = 0.997 / coeff1 = 0.127 / coeff2 = 0.350 / ppm = 359.84
bio_mult[1996] = 0.999 / coeff1 = 0.127 / coeff2 = 0.350 / ppm = 361.46
bio_mult[1997] = 1.000 / coeff1 = 0.127 / coeff2 = 0.350 / ppm = 363.15
```
```
wue_mult[1987] = 1.003 / coeff1 = 22.464 / coeff2 = -0.531 / ppm = 348.64
wue_mult[1988] = 1.000 / coeff1 = 22.464 / coeff2 = -0.531 / ppm = 350.74
wue_mult[1989] = 0.998 / coeff1 = 22.464 / coeff2 = -0.531 / ppm = 352.49
...
wue_mult[1995] = 0.987 / coeff1 = 22.464 / coeff2 = -0.531 / ppm = 359.84
wue_mult[1996] = 0.984 / coeff1 = 22.464 / coeff2 = -0.531 / ppm = 361.46
```

**Comment by dschlaep** [comment]
@jbbradford John, could you please review this issue? Do we expect/request that the multipliers are 1 in the year when CO2 = 360 ppm? If so this is a bug. Thanks!

**Comment by Zachary-Kramer** [comment]
@dschlaep was changing the coefficients all that was needed to close this issue?

**Comment by dschlaep** [comment]
Fixing the coefficients so that multipliers == 1 at 360 CO2 ppm was more of a different/sub problem (that no-one formulated as a github issue) and not #59 (i.e., explicitly have a reference concentration). 

Commit https://github.com/Burke-Lauenroth-Lab/SOILWAT2/commit/5387c0d71bc03132faf2f9581d3027e615c13aa7 doesn't explain why we changed values of coefficients: 
> Updated coefficient values were estimated so both multipliers to be equal/near 1 at a reference CO2 concentration of 360 ppm.
