### ISSUE TITLE
Outputs for 'CO2EFFECTS'

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/SOILWAT2#60]
Daily output for `CO2EFFECTS` produces only zeros even while yearly output shows non-zero values.

```
TIMESTEP dy, yr
...
CO2EFFECTS 		avg 		DY 		1 		end 		co2_effects
```

**Comment by Zachary-Kramer** [comment]
Correct. When we (Caitlin, Charlie, and I) initally laid out the requirements for CO2 output, we were only concerned about monthly and yearly. Thus, daily and weekly are not implemented. Now that CO2 has been developed further, it would be a good time to expand the output to daily and weekly.

**Comment by dschlaep** [comment]
If the CO2 values are the same for each day of a month, then output those for the daily output. If they CO2 values vary for each day, then output those daily values for the daily output.

Outputting 0s suggests that these are the daily values used in the simulation. This is incorrect.

**Comment by Zachary-Kramer** [comment]
SOILWAT2 now (locally) has daily and weekly output for CO2. Issue will be closed when rSOILWAT2 also has it.
