### ISSUE TITLE
Document input structure for carbon.in

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/SOILWAT2#64]
Explain how data for multiple scenarios can be entered.

**Comment by Zachary-Kramer** [comment]
Where should it be documented? Carbon.in already has a very basic explanation: 

> To insert another scenario, simply use the same pattern as below

Should this just be expanded to provide a little more information? e.g. scenario name is at year 0

**Comment by dschlaep** [comment]
Explain the structure of the file
- scenario names by lines with a leading 0
- data by year and CO2 concentration in ppm
- data for multiple scenarios are appended to the same file

```
0             RCP45
# Year  PPM
1765	278.05158
1766	278.10615
...

0             RCP85
# Year  PPM
1765	278.05458
1766	278.08125
...

...
```
