### ISSUE TITLE
Lots of compiler warnings and notes when compiling (at least as submodule to Rsoilwat)

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/SOILWAT2#7]
- SW_VegEstab.c:531:53: warning: taking the absolute value of unsigned type
    'LyrIndex' (aka 'unsigned int') has no effect [-Wabsolute-value]
      min_transp_lyrs = fmin(SW_Site.n_transp_lyrs_tree, fmin(S...
                                                         ^
- ./generic.h:41:23: note: expanded from macro 'fmin'
  #define fmin(a,b) ( ( LT((a),(b)) ) ? (a) : (b))
                    ^
- ./generic.h:181:18: note: expanded from macro 'LT'
  #define LT(x,y)  isless2(x,y)
               ^
- ./generic.h:173:37: note: expanded from macro 'isless2'
  #define isless2(x, y) ((x) < ((y) - GET_F_DELTA(x, y)))
                                  ^
- note: (skipping 3 expansions in backtrace; use -fmacro-backtrace-limit=0
    to see all)
- ./generic.h:41:31: note: expanded from macro 'fmin'
  #define fmin(a,b) ( ( LT((a),(b)) ) ? (a) : (b))
                            ^
- ./generic.h:181:28: note: expanded from macro 'LT'
  #define LT(x,y)  isless2(x,y)
                         ^
- ./generic.h:173:32: note: expanded from macro 'isless2'
  #define isless2(x, y) ((x) < ((y) - GET_F_DELTA(x, y)))
                             ^
- SW_VegEstab.c:531:53: note: remove the call to 'fabs' since unsigned
    values cannot be negative
- ./generic.h:41:23: note: expanded from macro 'fmin'
  #define fmin(a,b) ( ( LT((a),(b)) ) ? (a) : (b))
                    ^
- ./generic.h:181:18: note: expanded from macro 'LT'
  #define LT(x,y)  isless2(x,y)
               ^
- ./generic.h:173:37: note: expanded from macro 'isless2'
  #define isless2(x, y) ((x) < ((y) - GET_F_DELTA(x, y)))
                                  ^
- note: (skipping 3 expansions in backtrace; use -fmacro-backtrace-limit=0
    to see all)
- ./generic.h:41:31: note: expanded from macro 'fmin'
  #define fmin(a,b) ( ( LT((a),(b)) ) ? (a) : (b))
                            ^
- ./generic.h:181:28: note: expanded from macro 'LT'
  #define LT(x,y)  isless2(x,y)
                         ^
- ./generic.h:173:32: note: expanded from macro 'isless2'
  #define isless2(x, y) ((x) < ((y) - GET_F_DELTA(x, y)))

**Comment by charlieduso** [comment]
I'll be working on resolving these in the clean-up branch that I created.

**Comment by dschlaep** [comment]
close #7 with pr #83
