### ISSUE TITLE
Reference for documentation of RandBeta function

### ISSUE THREAD

**Issue by CaitlinA** [Burke-Lauenroth-Lab/SOILWAT2#81]
RandBeta or 'genbet' might need a reference. If there is a reference please add it in the doxygen documentation type placeholder provided.

Rui, did you develop the code from scratch? Or did you copy-paste from some external source? If the latter, then provide appropriate reference(s) and license statements.

@2hua @dschlaep

**Comment by 2hua** [comment]
The beta function was copied from ranlib.  
Licensing:

    This code is distributed under the GNU LGPL license.

  Modified:

    19 September 2014

  Author:

    Original FORTRAN77 version by Barry Brown, James Lovato.
    C version by John Burkardt. 

 Reference:

    Russell Cheng,
    Generating Beta Variates with Nonintegral Shape Parameters,
    Communications of the ACM,
    Volume 21, Number 4, April 1978, pages 317-322.

**Comment by dschlaep** [comment]
close #81 with pr #83
