### ISSUE TITLE
Global variable 'Old_SW_VegProd' unused -- do we still need it?

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/SOILWAT2#92]
- Global variable 'Old_SW_VegProd' was introduced by commit 12a99e8f8bffa774c5c5df218f1b91605394ca73 (three years ago).

- Function `SW_VPD_read()` sets it as copy of `SW_VegProd`.

- It is not used by any code by `SOILWAT2`. Does this variable have any (hidden) need to exist? If not, can we delete it? @ashishtiwari2006 @BrendenBe1 @kpalmqui

**Comment by BrendenBe1** [comment]
It seems like it serves no purpose. I commented it out and ran STEPWAT and SOILWAT standalone and noticed no difference in output and no errors occured.

**Comment by kpalmqui** [comment]
I concur - we can delete it.

**Comment by dschlaep** [comment]
Thanks for checking!
